#!/bin/bash

UPDATE_AFTER=43200 # 12 hours


arch_last_update() {
	LOG_DATE=$(grep 'synchronizing package lists' /var/log/pacman.log | \
               tail -1 | awk '{print $1" "$2}' | tr -d \[\])
	date -d "$LOG_DATE" +%s
}

arch_update_repo() {
	if ! sudo -n pacman -Sy &> /dev/null; then
		echo "out-of-date"
		exit 1
	fi
}

arch_num_updates() {
	pacman -Qu | wc -l
}

void_last_update() {
	stat -c '%Y' '/var/db/xbps/https___repo_voidlinux_eu_current'
}

void_update_repo() {
	if ! sudo -n xbps-install -S &> /dev/null; then
		echo "out-of-date"
		exit 1
	fi
}

void_num_updates() {
	xbps-install -nu | wc -l
}

if [ -f /etc/os-release ]; then
	if grep -q arch /etc/os-release; then
		OS='arch'
	elif grep -q void /etc/os-release; then
		OS='void'
	else
		echo "ERROR: I currently don't have support for your distro"
		exit 1
	fi
else
	echo "ERROR: /etc/os-release does not exist, so I can't tell which distro you're using!"
	exit 1
fi


CURRENT_TIME=$(date '+%s')
LAST_UPDATE=$(eval ${OS}_last_update)

if ((CURRENT_TIME-LAST_UPDATE > UPDATE_AFTER)); then
	eval ${OS}_update_repo
fi

echo "$(eval ${OS}_num_updates)"

